name: oulad
version: 1.0.0
config-version: 2

profile: oulad

model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots

target-path: target
clean-targets:
  - target
  - logs

models:
  oulad:
    bronze:
      +materialized: view
      +schema: bronze
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold
      +incremental_strategy: merge

tests:
  +schema: gold
