-- Bronze source declarations
-- These tables are created by load_to_bronze.py (Python ingestion script)
-- and are read-only from Dataform's perspective.

declare ${self().getName()} default as (
  SELECT * FROM bronze.courses
);

declare bronze_assessments default as (
  SELECT * FROM bronze.assessments
);

declare bronze_vle default as (
  SELECT * FROM bronze.vle
);

declare bronze_student_info default as (
  SELECT * FROM bronze.student_info
);

declare bronze_student_registration default as (
  SELECT * FROM bronze.student_registration
);

declare bronze_student_assessment default as (
  SELECT * FROM bronze.student_assessment
);

declare bronze_student_vle default as (
  SELECT * FROM bronze.student_vle
);
