config {
  type: "table",
  schema: "dv",
  tags: ["dv", "satellite"],
  assertions: {
    nonNull: ["hk_student"],
  },
}

SELECT DISTINCT
  TO_HEX(SHA256(CAST(id_student AS STRING))) AS hk_student,
  gender,
  age_band,
  highest_education,
  disability,
  TO_HEX(SHA256(CAST(region AS STRING))) AS region_hashed,
  TO_HEX(SHA256(CAST(imd_band AS STRING))) AS imd_band_hashed,
  studied_credits,
  num_of_prev_attempts,
  CURRENT_TIMESTAMP() AS dv_load_date,
  'OULAD' AS dv_source
FROM ${ref("bronze_student_info")}
